### ISSUE TITLE
The LFS file of your dataset seems to have exceeded quota limit and hence unable to load the repo with git clone. Is there a way I can get direct access to the dataset.

### ISSUE THREAD

**Issue by HarxSan** [RenqiChen/The_Crop#2] opened 2024-09-01 18:09 UTC
If I may actually we need it for our research work.

**Comment by RenqiChen** [comment] 2024-09-12 02:26
The problem may be caused by the dataset in train/data/SFT_ruozhiba.json. You can directly down the ZIP of this repo. If the LFS file is not downloaded successfully, you can go to https://github.com/paralym/COIG-CQIA to download this dataset.

**Comment by RenqiChen** [comment] 2024-09-12 02:29
COIG-CQIA is a general public dataset, and our dataset and benchmark will be released soon after the paper review and will be put on Google Drive. We will notify you when we release our resources and thanks for your patience.

**Closed as completed** 2024-09-14 01:20 UTC
